var initializeculture =
{
    remove: 'حذف کردن',
    update: 'ویرایش',
    add: 'اضافه کردن',
    submit: 'ثبت',
    close: 'انصراف',
    save: 'ثبت',
    SendComplete: 'ارسال با موفقیت انجام شد',
    cancel: "انصراف",
    ok: "تایید",
    notfindany: "موردی یافت نشد",
    new: "جدید",
    form_title: "جدید",
    error: "خطا",
    editform: "ویرایش",
    areyousureyouwantlockthisitem: 'آیا مایل به قفل کردن این آیتم هستید؟ ',
    areyousureyouwantunlockthisitem: 'آیا مایل به باز کردن قفل این آیتم هستید؟ ',
    areyousureyouwantremovethisitem: 'آیا مایل به حذف کردن این آیتم هستید؟ ',
    areyousureyouwantsuspendthisitem: 'آیا مایل به خروج این پروانه از تعلیق هستید؟ ',
    areyousureyouwantpublishthisitem: 'آیا مایل به عمومی سازی کردن این آیتم هستید؟ ',
    areyousureyouwantunpublishthisitem: 'آیا مایل به غیر عمومی سازی کردن این آیتم هستید؟ ',
    areyousureyouwantconfirmthisitem: 'آیا مایل به تایید کردن این آیتم هستید؟ ',
    areyousureyouwantunconfirmthisitem: 'آیا مایل به لغو کردن این آیتم هستید؟ ',
    areyousureyouwantsetdefaultlanguage: "آیا مایل به تنظیم به عنوان زبان پیشفرض می باشید؟",
    RelatedArticle: 'آیا مایل هستید این مقاله رو به لیست مقالات مرتبط متصل کنید؟',
    pleasewaite: 'لطفا منتظر بمانید...',
    edithasbeensuccessfully:"ویرایش با موفقیت انجام شد.",
    newitemsuccessfully: "آیتم جدید با موفقیت ثبت گردید.",
    nomatchesfound: "موردی یافت نشد",
    nodataavailableintable: "موردی یافت نشد",
    areyousureyouwantremoveselecteditem: "آیا مایل به حذف موارد انتخابی هستید؟",
    publish:"نمایش مقاله",
    unpublish: "تعلیق نمایش"
}